// Generated by Structorizer 3.29-01 

/**
 * This diagram describes the main() method
 */
public class HelloWorld
{



	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		// TODO: Check and accomplish variable declarations: 
		
		System.out.println("Hello, world");
	}

}